name: maimai database updater

on:
  # Every 6 hours, at :25, every day
  schedule:
    - cron: '25 1,7,13,19 * * *'
  workflow_dispatch:

jobs:
  maimai-database-updater:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git
        run : |
          git config --global user.email "noreply@github.com"
          git config --global user.name "GitHub Actions"
          git fetch origin
          git checkout gh-pages

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Build
        run: |
          npm install
          npm run build

      - name: Fetch and parse file
        run: |
          mkdir -p external
          curl https://dp4p6x0xfi5o9.cloudfront.net/maimai/data.json -o external/arcade-songs-maimai.json
          curl https://raw.githubusercontent.com/zvuc/otoge-db/refs/heads/master/maimai/data/music-ex.json -o external/otoge-db.json
          curl https://raw.githubusercontent.com/zvuc/otoge-db/refs/heads/master/maimai/data/music-ex-intl.json -o external/otoge-db-intl.json
          node build/index.js external/arcade-songs-maimai.json external/otoge-db.json external/otoge-db-intl.json external/magic.json
          node build/generate-plate-info.js external/arcade-songs-maimai.json external/plate-info

      - name: Push changes
        run: |
          git add external
          if output=$(git status --porcelain) && [ -z "$output" ]; then
            echo "No changes to commit."
          else
            git commit -m "Update maimai constants $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
            git push origin gh-pages
            echo "Commited changes."
          fi
