name: maimai database updater

on:
  # Every 6 hours, at :25, every day
  schedule:
    - cron: '25 1,7,13,19 * * *'
  workflow_dispatch:

jobs:
  maimai-database-updater:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4

      - name: Configure Git
        run : |
          git config --global user.email "noreply@github.com"
          git config --global user.name "GitHub Actions"
          git fetch origin
          git checkout gh-pages

      - name: Fetch file
        run: |
          mkdir -p external
          curl https://dp4p6x0xfi5o9.cloudfront.net/maimai/data.json -o external/arcade-songs-maimai.json

      - name: Push changes
        run: |
          git add external
          if output=$(git status --porcelain) && [ -z "$output" ]; then
            echo "No changes to commit."
          else
            git commit -m "Update constants from arcade-songs $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
            git push origin gh-pages
            echo "Commited changes."
          fi
